<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTu49BzQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTu49BzQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTu49BzQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTu49BzQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTu49BzQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Tu49BzQ',
    'container.build_id' => '9f365dbc',
    'container.build_time' => 1676715620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTu49BzQ');
