<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIVppiBl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIVppiBl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIVppiBl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIVppiBl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIVppiBl\App_KernelDevDebugContainer([
    'container.build_hash' => 'IVppiBl',
    'container.build_id' => 'b24d90ee',
    'container.build_time' => 1676902850,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIVppiBl');
